AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.5

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/AbcSize:
  Max: 20
Metrics/ClassLength:
  Max: 250
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Max: 7

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/SymbolArray:
  Enabled: true
